const { checkJWT } = require('../helpers/jwt');
const {io} = require('../index');
const {connectedUser, disconnectedUser, saveMessage} = require('../controllers/socket');

// Mensajes de Sockets
io.on('connection', client => {
    console.log('Cliente conectado');

    const [isValid, uid] = checkJWT(client.handshake.headers['x-token']);

    // verify authentication
    if(!isValid) { 
        return client.disconnect();
    }

    //authenticated client
    connectedUser(uid);  

    //enter user to specific room 
    // for default one is the global room where all the devices are connected
    // client.id is generated by the socket server automatically
    // I want to add the user to a individual room
    // the individual room is going to have the db uid.

    client.join(uid);

    //listen the client message
    client.on('message-personal', async (payload)=>{
        //TODO: save message
        await saveMessage(payload);
        io.to(payload.to).emit('message-personal',payload);
    })

    client.on('disconnect', () => {
        disconnectedUser(uid);
        console.log('Cliente desconectado');
    });

  });
